# Generated by Django 2.2.12 on 2022-11-01 07:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0002_auto_20221101_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='jenis',
            name='nama',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
