# Generated by Django 4.1.2 on 2022-11-24 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0003_jenis_nama'),
    ]

    operations = [
        migrations.CreateModel(
            name='JenisIkan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('ket', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ikan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kodeikan', models.CharField(max_length=50)),
                ('nama', models.CharField(max_length=50)),
                ('jml', models.IntegerField()),
                ('harga', models.BigIntegerField()),
                ('link', models.CharField(blank=True, max_length=150)),
                ('jenis_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='landingpage.jenisikan')),
            ],
        ),
    ]
